[project]
name = "hot100"
version = "0.1.0"
description = "LeetCode hot 100"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[project.scripts]
# 格式：命令名 = 包名.文件名:函数名
max_sliding_window = "leetcode.maxSlidingWindow:main"
search_matrix = "leetcode.searchMatrix:main"
num_squares = "leetcode.numSquares:main"
move_zeroes = "leetcode.moveZeroes:main"
find_duplicate = "leetcode.findDuplicate:main"
median_finder = "leetcode.medianFinder:main"
length_of_lis = "leetcode.lengthOfLIS:main"
coin_change = "leetcode.coinChange:main"
top_k_frequent = "leetcode.topKFrequent:main"
decode_string = "leetcode.decodeString:main"
can_partition = "leetcode.canPartition:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}