[project]
name = "hot100"
version = "0.1.0"
description = "LeetCode hot 100"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[project.scripts]
# 格式：命令名 = 包名.文件名:函数名
max_sliding_window = "leetcode.maxslidingwindow:main"
search_matrix = "leetcode.searchmatrix:main"
num_squares = "leetcode.numsquares:main"
move_zeroes = "leetcode.movezeroes:main"
find_duplicate = "leetcode.findduplicate:main"
median_finder = "leetcode.medianfinder:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}